### ISSUE TITLE
✨ Multicaller

### ISSUE THREAD

**Issue by Vectorized** [Vectorized/solady#278]
Port of the famous multicall everyone uses.

Probably better if in a new repo, deployed to multiple chains via create2, mined with 6 leading zeros. 

Use the direct return trick in Multicallable. Seriously, it can save thousands of gas for certain use cases.

I'm too lazy and busy to do this. Lmk if u want to do it.

**Comment by Atarpara** [comment]
@Vectorized  I can work on this. If you could provide more context about this. It would really helpful. If anyone want to work with me on this. DM me on Discord. (Atarpara#3852)

**Comment by tannakartikey** [comment]
I'll look into it

**Comment by tannakartikey** [comment]
@Vectorized, the Multicallable in this repo is to call multiple methods on the contract itself. In this issue, you are talking about making multiple calls to an external contract, right? Something like this?

```solidity
function multicall(address[] calldata targets, bytes[] calldata data) external payable returns (bytes[] memory)
```

**Comment by tannakartikey** [comment]
@Vectorized, I created a repo. At the moment, it supports the call to only one contract. Almost all the code and the tests are from this repo only.

I just made a small change. I used `call` instead of `delegatecall` since it should not use the storage of the calling contract. Due to that `msg.sender` can not be passed and the tests are failing. Not passing `msg.value` either. 

@Vectorized, can you please tell me if this is going in the right direction? Next, I want to modify the code so that it can support calling multiple contracts.

**Comment by Vectorized** [comment]
Oh, we are trying to recreate https://github.com/makerdao/multicall/blob/master/src/Multicall2.sol
and https://github.com/makerdao/multicall/blob/master/src/Multicall.sol @tannakartikey 

Do you have a discord ID? I'll invite you to the group chat.

**Comment by tannakartikey** [comment]
@Vectorized `kart#2109`. Thansk

**Comment by Vectorized** [comment]
Thanks all for the hard work.

https://github.com/Vectorized/multicaller
