### ISSUE TITLE
✨ ERC1967Factory for beacon proxies

### ISSUE THREAD

**Issue by meetmangukiya** [Vectorized/solady#528]

**Comment by Vectorized** [comment]
Unfortunately, this is not on the roadmap.

I'll recommend OpenZeppelin if you need the Beacon proxy.

**Comment by Atarpara** [comment]
@Vectorized Can you share the roadmap with me? I have some free time.

**Comment by meetmangukiya** [comment]
I see. Yeah, had to use OZ as dependency just for beacon proxies would be nice if it gets in solady too.

**Comment by Vectorized** [comment]
If you are ok with no Etherscan support (i.e. no read and write to proxy tabs), you can implement it as a ERC1167 minimal proxy -> ERC1967Proxy. 

More efficient for small calldata sizes too, as it avoids an extra SLOAD (but calldata has to be copied).

But I feel Etherscan support is more important if your product is aimed towards mass market.

Anyway, if you are going with Beacon pattern, it means max gas savings isn't the highest priority, so OpenZeppelin is probably ok.

**Comment by Vectorized** [comment]
Due to circumstances (some imperfections found in V1 during the audit), we are considering the possibility of a V2 with beacon capabilities. 

But this won’t be an easy task. Two new bytecode contracts (beacon, beaconProxy) must be written. It’s gonna be really insane. 

At this point, this factory is more of making an artistic statement. If funds can be provided to cover the development and audit, we can make this closer to reality.

**Comment by Vectorized** [comment]
@waynehoover I think right now I don’t have brain juice for making the V2 factory. 😂 Estimated effort is 2 weeks (not including time to mine the address). And I gotta nerdsnipe others to look into it for safety. 

Even though I really want to make it for the joy of it. 🥹

**Comment by Atarpara** [comment]
I think it is under audit process by spearbit. @Vectorized  correct me if am i wrong.

**Comment by Vectorized** [comment]
@waynehoover @Atarpara Yes, currently under audit. Finishing soon, tentatively by Aug 25th.

So far no vulnerabilities. :)
